apply plugin: 'com.android.application'

android {
    compileSdk appTargetSdk
    defaultConfig {
        minSdk appMinSdk
        targetSdk appTargetSdk
        applicationId "com.miyuan.obd"
        versionCode 1400
        versionName "3.1"
        flavorDimensions "default"

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
            }
        }

        productFlavors {
            inside {
                buildConfigField 'String', "HOST", '"http://47.92.101.179:8020/"'
            }

            formal {
                buildConfigField 'String', "HOST", '"http://box.1668288.com/"'
            }
        }

        signingConfigs {
            release {
                storeFile file("../key/miyuan_android.keystore")
                storePassword "miyuan2018"
                keyAlias "miyuan_android"
                keyPassword "miyuan2018"
                v2SigningEnabled true
                v1SigningEnabled true
            }
        }

        lintOptions {
            checkReleaseBuilds false
            abortOnError false
        }

        buildTypes {
            debug {
                minifyEnabled false
                signingConfig signingConfigs.release
                ndk {
                    abiFilters 'armeabi-v7a', 'arm64-v8a'
                }
            }

            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                signingConfig signingConfigs.release
                ndk {
                    abiFilters 'armeabi-v7a', 'arm64-v8a'
                }
            }
        }

        sourceSets { // 从ANT迁移的工程，可以使用 sourceSets 来配置工程结构.
            main {
                manifest.srcFile 'AndroidManifest.xml'
                res.srcDirs = ['res']

                java.srcDirs = ['src']
                aidl.srcDirs = ['src']
                renderscript.srcDirs = ['src']

                assets.srcDirs = ['assets']
                jniLibs.srcDirs = ['libs'] // 配置此处才会打包jni 的.so 文件
//            jni.srcDirs=['jni']
            }
        }

//        applicationVariants.all { variant ->
//            if (variant.buildType.name != "debug") {
//                variant.getPackageApplicationProvider().get().outputDirectory = new File(project.rootDir.absolutePath + "/release")
//            }
//            variant.getPackageApplicationProvider().get().outputScope.apkDatas.forEach { apkData ->
//                apkData.outputFileName =
//                        variant.flavorName + "_" + "OBD" +
//                                ".apk"
//            }
//        }

//        compileOptions {
//            coreLibraryDesugaringEnabled true
//            sourceCompatibility JavaVersion.VERSION_1_8
//            targetCompatibility JavaVersion.VERSION_1_8
//        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    configurations.all {
        resolutionStrategy {
            force 'org.jetbrains.kotlin:kotlin-stdlib:1.6.21'
        }
    }
}
dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api project(path: ':core')
    api project(path: ':obd_sdk')
    api 'org.simple:androideventbus:1.0.5.1'
    api 'com.alibaba:fastjson:1.2.69'
    api 'com.gyf.barlibrary:barlibrary:2.3.0'
    api 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar'
    api 'me.jessyan:rxerrorhandler:2.1.1'
    api 'com.contrarywind:Android-PickerView:4.1.8'
    api 'io.reactivex.rxjava2:rxjava:2.2.21'
    api 'com.jungly:gridPasswordView:0.3'
    api 'androidx.recyclerview:recyclerview:1.3.0'
//    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation 'androidx.appcompat:appcompat:1.6.0'
}
